---
- name: Deploy Laravel App to Server
  hosts: all
  vars:
    deploy_path: "/var/www/html/kimheng"
  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "{{ deploy_path }}"
        state: directory
        mode: '0755'

    - name: Copy Laravel files to the server
      ansible.posix.synchronize:
        src: "{{ workspace }}/"
        dest: "{{ deploy_path }}/"
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=database/database.sqlite"  # <-- ADD THIS
          - "--exclude=.env"

    - name: Set permissions for storage and bootstrap/cache
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
      loop:
        - "{{ deploy_path }}/storage"
        - "{{ deploy_path }}/bootstrap/cache"